In [1]:
import numpy as np
import sys

The Basics

In [2]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [3]:
b = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print(b)
print("Dimension are ", b.ndim)

print("Rows are {} and Columns {} are ".format(*b.shape))
print("Data type is {}".format(b.dtype))


[[1. 2. 3.]
 [4. 5. 6.]]
Dimension are  2
Rows are 2 and Columns 3 are 
Data type is float64


In [4]:
#get the size 
print('{} Byte(s)'.format(a.itemsize)) # size of 1 element or lengt of an element in bytes
print('{} Byte(s)'.format(a.size)) # number of elements
print('{} Byte(s)'.format(a.nbytes)) # size * itemsize


2 Byte(s)
3 Byte(s)
6 Byte(s)


Accessing/Changing specific elements, rows, columns etc

In [5]:
t = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(t)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [6]:
#get specific element [row,column]
#print(t[1,5])
print(t[1,-2])
print(t.shape)

13
(2, 7)


In [7]:
#getting specific row or column
print(t[0,:])
print(t[:,1])
print(t[:,0:7:2])


[1 2 3 4 5 6 7]
[2 9]
[[ 1  3  5  7]
 [ 8 10 12 14]]


In [8]:
t[1,5] = 100
t[0,:] = [21,22,23,24,25,26,27]
print(t)

[[ 21  22  23  24  25  26  27]
 [  8   9  10  11  12 100  14]]


In [9]:
#3D array
d3_array = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[12,13,14]]])
print("This is a {}D array".format(d3_array.ndim))
print(d3_array)

This is a 3D array
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [12 13 14]]]


In [10]:
#to get specific element from a 3D array, work outside in
print(d3_array[0,1,2])
print(d3_array[:,1,:])

6
[[ 4  5  6]
 [12 13 14]]


Initializing Different types of Arrays

In [11]:
#All zeros matrix
print(np.zeros((4,3,4)))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
